Resources:          
  myUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: trish
      LoginProfile: # specify a password for this user
        Password: Password01!
        PasswordResetRequired: true # make this user to set a new password on next sign-in
        # Groups: # attach this user to the list of existing groups
        #   - groupA
  myGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: Developers2 # give a name to this group
      Path: '/'
      ManagedPolicyArns: # list of ARNs of IAM managed policies that you want to attach to the group
        - arn:aws:iam::aws:policy/AWSCloud9Administrator # provide administrator access to AWS Cloud9
        # - arn:aws:iam::111111111111:policy/customerManagedBlahBlahPolicy # use your own customer managed policy specifying its ARN
      Policies: # list of inline policy documents that are embedded in the group
        - PolicyName: inlineCloudWatchLogsPolicy # give a unique name to this policy
          PolicyDocument: # JSON policy document
            Version: '2012-10-17'
            Statement: # provide write permissions to CloudWatch Logs
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream*'
                  - 'logs:PutLogEvents'
                Resource: '*'
  myUserToGroupAddition:
    DependsOn:
      - myUser
      - myGroup
    Type: 'AWS::IAM::UserToGroupAddition'
    Properties:
      GroupName: Developers2 # existing group name
      Users: # list of existing user names
          - trish
